### ISSUE TITLE
pip installation failed on mac osx Version 13.2 (22D49)

### ISSUE THREAD

**Issue by pankajarm** [steamship-core/steamship-langchain#21]
Apple MacBook Pro 14 M2 Pro 2023
Mac OSX Version 13.2 (22D49)

conda 23.1.0
python 3.10.9
pip 22.3.1

Here are the steps:
conda create -n ss-lc-env python
conda activate ss-lc-env
pip install steamship-langchain

.......
     fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

<img width="1155" alt="Screenshot 2023-02-24 at 4 11 31 PM" src="https://user-images.githubusercontent.com/1421737/221323914-609aacd2-6a15-4f97-b5ad-9dac02610461.png">

**Comment by douglas-reid** [comment]
@pankajarm thanks for the report. I hadn't tried running an install on a clean dev machine.

unfortunately, there is no easy way around the root issue. the `lxml` requirement comes from `tiktoken`. Our OpenAI adapter uses the `tiktoken` package to provide [`get_num_tokens()`](https://github.com/steamship-core/steamship-langchain/blob/main/src/steamship_langchain/llms/openai.py#L131-L136). this is also the case with `langchain` as it also [uses `tiktoken` for similar environments](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L414-L420) (Steamship uses Python 3.8+).

I'm honestly not sure which is the better experience. Would you prefer that the `pip install` completes, but then at runtime you discover you need to install `tiktoken`? Or this upfront failure?

Do you intend on using the LLMs?  Or only some other part of the package?
