### ISSUE TITLE
How to loading multiple html files which span across multiple directories to vector store?

### ISSUE THREAD

**Issue by limcheekin** [steamship-core/steamship-langchain#32]
Thanks for sharing the example at https://github.com/steamship-core/steamship-langchain/tree/main/examples/qa_with_sources.

The existing code at https://github.com/steamship-core/steamship-langchain/blob/main/examples/qa_with_sources/server/api.py#L28 is to add a single text file to the SteamshipVectorStore.

What if I have multiple HTML files which span across multiple directories and its file location is important as it is the same as the structure of the sources from "https://...../".

Please advise. Thank you.

**Comment by douglas-reid** [comment]
@limcheekin there are a couple of things you might want to look at for inspiration:

- [DirectoryLoader](https://github.com/steamship-core/steamship-langchain/blob/main/src/steamship_langchain/file_loaders/directory.py)
- [SphinxSiteLoader(s)](https://github.com/steamship-core/steamship-langchain/blob/main/src/steamship_langchain/file_loaders/sphinx.py)

Where location is concerned, you may want to use something like [this line](https://github.com/steamship-core/steamship-langchain/blob/main/src/steamship_langchain/file_loaders/sphinx.py#L97).

Depending on the format of your HTML and what you want to do with it, you may need to adapt the loaders to match your needs.

**Comment by limcheekin** [comment]
Thanks for quick response.

I just dropped an email message to Steamship support team regarding:
```
I got the following message on the first deployment:
You have reached the preview usage limit. Please sign up for a plan at https://steamship.com/account/plan to continue.
```

Not sure how I reached the preview usage limit as I haven't start using it.

Will try your suggestions after the issue above resolved.

**Comment by douglas-reid** [comment]
@limcheekin were you able to get setup with a Steamship account?

**Comment by limcheekin** [comment]
I am not using Steamship account now.
