### ISSUE TITLE
[model]How to use gpt-4 in steamship-langchain

### ISSUE THREAD

**Issue by VanderBieu** [steamship-core/steamship-langchain#41]
I am pretty sure that I am on the developer plan and I have tested my access to gpt-4 instance. But I still cannot get access by specifying model_name:LLMChain(
    llm=OpenAI(client=client, temperature=0,model_name='gpt-4'),
    prompt=prompt,
    verbose=True,
    memory=ConversationBufferWindowMemory(chat_memory=chat_memory, k=2),
)

error info:
1 validation error for OpenAIChat
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by douglas-reid** [comment]
@VanderBieu It looks like the code you posted uses `OpenAI` but your error message is `OpenAIChat`. Is there potentially a copy/paste error involved?

Did you check to make sure that you have code like: `from steamship_langchain.llms.openai import OpenAI, OpenAIChat` in your file?

**Comment by douglas-reid** [comment]
@VanderBieu i was able to identify the source of the issue you are having. Working on a fix.

**Comment by douglas-reid** [comment]
In the short term, use steamship_langchain's `OpenAIChat` class directly as a workaround.

**Comment by douglas-reid** [comment]
https://github.com/steamship-core/steamship-langchain/pull/42

**Comment by douglas-reid** [comment]
Should be fixed in 0.0.19 release.
