### ISSUE TITLE
open csv/json/pdf files with File class

### ISSUE THREAD

**Issue by YoungGoofy** [steamship-core/steamship-langchain#46]
Hey all 
I am trying to process a ``csv`` file, but I do not understand how to work with the class ``File``.
Can you give me a small example of how to work with non-text files?

**Comment by douglas-reid** [comment]
@YoungGoofy do the docs at https://docs.steamship.com/data/files.html help? Are you looking for more information specific to CSVs? Or are you also thinking about images or other formats?

**Comment by douglas-reid** [comment]
closing, as it has been a month with no updates. please re-open if you would like more info here.
