### ISSUE TITLE
Quickstart is incomplete

### ISSUE THREAD

**Issue by sorenwacker** [steamship-core/steamship-langchain#47]
https://steamship-langchain.readthedocs.io/en/0.0.12/getting_started/getting_started.html

Would be nice it the example in the quickstart would be complete.

I am getting

> NameError: name 'Steamship' is not defined

and 

> alidationError: 1 validation error for OpenAI client  none is not an allowed value (type=type_error.none.not_allowed)

with the provided snippets.

**Comment by douglas-reid** [comment]
@sorenwacker I'm sorry you are having trouble.

I just tried it out, and I think I see where you _may_ be having issues. You definitely MUST include `client` as an argument to the `OpenAI` class, but I suspect you didn't update the import statement as highlighted in the diff.

Here's my full working example (with only the handle for my package removed):

```python
from steamship import Steamship
from steamship_langchain.llms import OpenAI
from steamship.invocable import PackageService, post

class JokeWizard(PackageService):

    @post("generate")
    def generate(self) -> str:
        llm = OpenAI(
            client=self.client,
            model_name="text-ada-001",
            n=2, best_of=2,
            temperature=0.9)

        return llm("Tell me a joke")



def call():
  with Steamship.temporary_workspace() as client:
    package = client.use(<INSERT_YOUR_PACKAGE_HANDLE_HERE>)
    print(package.invoke("generate"))


if __name__ == "__main__":
  call()
```
